import React, { useState } from 'react';
import type { OutageRecord, TelecomStats } from '../types';

import { generateSmartFacts, simulateWhatIf } from '../utils/analytics';
import {
  Sparkles,
  Sliders,
  AlertOctagon,
  CheckCircle,
  Lightbulb,
  FileDown,
  TrendingUp,
  Award
} from 'lucide-react';
import confetti from 'canvas-confetti';
import { soundFX } from '../utils/soundEffects';

interface InsightsTabProps {
  records: OutageRecord[];
  stats: TelecomStats;
}

export const InsightsTab: React.FC<InsightsTabProps> = ({ records, stats }) => {
  const [fixedSitesCount, setFixedSitesCount] = useState<number>(2);
  const [exported, setExported] = useState<boolean>(false);

  const facts = generateSmartFacts(records);
  const simulation = simulateWhatIf(records, fixedSitesCount);

  const triggerExport = () => {
    soundFX.playSuccess();
    confetti({
      particleCount: 80,
      spread: 70,
      origin: { y: 0.6 }
    });
    setExported(true);

    // Generate markdown executive brief and download as file
    const reportContent = `ENGRO ENFRASHARE - NETWORK AVAILABILITY REPORT (NAR)
Executive Telemetry Brief
Generated: ${new Date().toLocaleString()}

1. EXECUTIVE SUMMARY
====================
- Overall Network Availability: ${stats.overallAvailability}%
- Total Monitored BTS Sites: ${stats.totalSites}
- Total Cumulative Downtime: ${stats.totalDowntimeHours} hours
- SLA Compliance Rate: ${stats.slaComplianceRate}%
- Active Outages in NOC: ${stats.activeIncidents}
- Average MTTR: ${stats.mttrAverageHours} hours

2. ROOT CAUSE & BOTTLENECK ANALYSIS
===================================
- Leading Cause: ${stats.topCategory}
- Top Bottleneck Node: ${stats.topWorstSite ? `${stats.topWorstSite.name} (${stats.topWorstSite.downtime}h downtime)` : 'None'}

3. SIMULATION & REMEDIATION PLAN
================================
- Resolving top ${fixedSitesCount} problematic sites jumps overall availability from ${stats.overallAvailability}% to ${simulation.simulatedAvailability}%.
- Total downtime recovered: ${simulation.downtimeSaved} hours.

Engine: Engro NAR Intelligence System
`;

    const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Engro_NAR_Executive_Brief_${new Date().toISOString().split('T')[0]}.txt`;
    link.click();
    URL.revokeObjectURL(url);

    setTimeout(() => setExported(false), 3000);
  };

  return (
    <div className="tab-content insights-tab">
      {/* Executive Action Card */}
      <div className="executive-card glass-panel glow-cyan">
        <div className="exec-header">
          <div className="exec-title">
            <Award className="text-amber" size={20} />
            <h3>Executive Intelligence Summary</h3>
          </div>
          <button className="export-action-btn" onClick={triggerExport}>
            <FileDown size={15} />
            <span>{exported ? 'Report Downloaded!' : 'Export Brief'}</span>
          </button>
        </div>
        <p className="exec-subtitle">
          Automated heuristic analytics generated by the Engro NAR engine for SLA optimization.
        </p>
      </div>

      {/* "What-If" SLA Simulator Tool */}
      <div className="simulator-card glass-panel">
        <div className="sim-header">
          <div className="sim-title-group">
            <Sliders size={18} className="text-emerald" />
            <h3>"What-If" SLA Availability Simulator</h3>
          </div>
          <span className="sim-badge">Interactive Heuristic</span>
        </div>

        <p className="sim-description">
          Slide to simulate the SLA recovery if top root-cause bottleneck sites are mitigated:
        </p>

        <div className="slider-control-box">
          <div className="slider-label-row">
            <span>Remediate Top Bottlenecks:</span>
            <strong className="slider-count-tag">{fixedSitesCount} Sites Fixed</strong>
          </div>

          <input
            type="range"
            min="1"
            max={Math.min(10, Math.max(1, records.length))}
            value={fixedSitesCount}
            onChange={(e) => {
              soundFX.playClick();
              setFixedSitesCount(Number(e.target.value));
            }}
            className="styled-range-slider"
          />

          <div className="slider-ticks">
            <span>1 Site</span>
            <span>{Math.min(5, records.length)} Sites</span>
            <span>{Math.min(10, records.length)} Sites</span>
          </div>
        </div>

        {/* Simulation Output Dashboard */}
        <div className="sim-results-grid">
          <div className="sim-stat-box">
            <span className="sim-stat-label">Current Availability</span>
            <span className="sim-stat-val cur">{stats.overallAvailability}%</span>
          </div>

          <div className="sim-arrow">➔</div>

          <div className="sim-stat-box highlight">
            <span className="sim-stat-label">Simulated Availability</span>
            <span className="sim-stat-val sim">{simulation.simulatedAvailability}%</span>
          </div>

          <div className="sim-stat-box">
            <span className="sim-stat-label">Downtime Saved</span>
            <span className="sim-stat-val saved">+{simulation.downtimeSaved}h</span>
          </div>
        </div>
      </div>

      {/* Automated Heuristic Anomaly Facts */}
      <div className="facts-header-row">
        <Sparkles size={16} className="text-cyan" />
        <h3>Automated Anomaly & Root Cause Insights</h3>
      </div>

      <div className="facts-list">
        {facts.map((fact) => {
          let IconComponent = Lightbulb;
          let borderClass = 'fact-info';

          if (fact.type === 'critical') {
            IconComponent = AlertOctagon;
            borderClass = 'fact-crit';
          } else if (fact.type === 'warning') {
            IconComponent = TrendingUp;
            borderClass = 'fact-warn';
          } else if (fact.type === 'positive') {
            IconComponent = CheckCircle;
            borderClass = 'fact-pos';
          }

          return (
            <div key={fact.id} className={`fact-card glass-panel ${borderClass}`}>
              <div className="fact-top">
                <div className="fact-title-wrapper">
                  <IconComponent size={18} className="fact-icon" />
                  <h4>{fact.title}</h4>
                </div>
                <span className="fact-impact-pill">{fact.metricImpact}</span>
              </div>

              <p className="fact-desc">{fact.description}</p>

              <div className="fact-recom">
                <strong>Recommended Action:</strong> {fact.recommendation}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
