import { OutageRecord } from '../types';

export const INITIAL_SAMPLE_RECORDS: OutageRecord[] = [
  {
    id: 'NAR-1001',
    siteId: 'KHI-042',
    siteName: 'Karachi Clifton Hub 1',
    region: 'South Region',
    downtimeHours: 4.8,
    availability: 98.67,
    timestamp: '2026-08-20',
    category: 'Commercial Grid Outage',
    status: 'Resolved',
    slaTarget: 99.90,
    rootCause: 'KE Feeder Trip - Gen Set auto-cranked with 12m delay',
    mttrMinutes: 288
  },
  {
    id: 'NAR-1002',
    siteId: 'LHR-118',
    siteName: 'Lahore Gulberg Tower 4',
    region: 'Central Region',
    downtimeHours: 1.2,
    availability: 99.66,
    timestamp: '2026-08-21',
    category: 'Fiber Cut',
    status: 'Resolved',
    slaTarget: 99.90,
    rootCause: 'Road construction metro cut main backhaul ring',
    mttrMinutes: 72
  },
  {
    id: 'NAR-1003',
    siteId: 'ISB-009',
    siteName: 'Islamabad Blue Area Node',
    region: 'North Region',
    downtimeHours: 0.3,
    availability: 99.92,
    timestamp: '2026-08-22',
    category: 'Hardware Glitch',
    status: 'Resolved',
    slaTarget: 99.90,
    rootCause: 'Rectifier module rebooted automatically',
    mttrMinutes: 18
  },
  {
    id: 'NAR-1004',
    siteId: 'PSH-074',
    siteName: 'Peshawar Hayatabad Sector 3',
    region: 'North Region',
    downtimeHours: 6.5,
    availability: 98.19,
    timestamp: '2026-08-22',
    category: 'Genset Fuel Exhaustion',
    status: 'Resolved',
    slaTarget: 99.90,
    rootCause: 'Severe road block delayed diesel delivery truck',
    mttrMinutes: 390
  },
  {
    id: 'NAR-1005',
    siteId: 'MUX-015',
    siteName: 'Multan Cantt Micro-Cell',
    region: 'Central Region',
    downtimeHours: 2.1,
    availability: 99.41,
    timestamp: '2026-08-23',
    category: 'Solar / Battery Depletion',
    status: 'Resolved',
    slaTarget: 99.90,
    rootCause: 'Consecutive cloudy days exceeded battery backup reserve',
    mttrMinutes: 126
  },
  {
    id: 'NAR-1006',
    siteId: 'QTA-028',
    siteName: 'Quetta Zarghoon Road Mast',
    region: 'South Region',
    downtimeHours: 8.4,
    availability: 97.66,
    timestamp: '2026-08-23',
    category: 'Fiber Cut',
    status: 'Investigating',
    slaTarget: 99.90,
    rootCause: 'Optical path breakdown on Highway link 4B',
    mttrMinutes: 504
  },
  {
    id: 'NAR-1007',
    siteId: 'FSD-061',
    siteName: 'Faisalabad Textile City Base',
    region: 'Central Region',
    downtimeHours: 0.9,
    availability: 99.75,
    timestamp: '2026-08-24',
    category: 'Commercial Grid Outage',
    status: 'Resolved',
    slaTarget: 99.90,
    rootCause: 'Transformer maintenance switch by FESCO',
    mttrMinutes: 54
  },
  {
    id: 'NAR-1008',
    siteId: 'RWP-088',
    siteName: 'Rawalpindi Saddar BTS',
    region: 'North Region',
    downtimeHours: 1.8,
    availability: 99.50,
    timestamp: '2026-08-24',
    category: 'Genset Fuel Exhaustion',
    status: 'Active',
    slaTarget: 99.90,
    rootCause: 'Alternator overheat during peak load',
    mttrMinutes: 108
  },
  {
    id: 'NAR-1009',
    siteId: 'HYD-033',
    siteName: 'Hyderabad Auto Bhan Spine',
    region: 'South Region',
    downtimeHours: 0.5,
    availability: 99.86,
    timestamp: '2026-08-24',
    category: 'Transmission Jitter',
    status: 'Resolved',
    slaTarget: 99.90,
    rootCause: 'Microwave alignment drift due to heavy wind gust',
    mttrMinutes: 30
  },
  {
    id: 'NAR-1010',
    siteId: 'SKT-019',
    siteName: 'Sialkot Export Zone Rooftop',
    region: 'Central Region',
    downtimeHours: 0.2,
    availability: 99.94,
    timestamp: '2026-08-24',
    category: 'Hardware Glitch',
    status: 'Resolved',
    slaTarget: 99.90,
    rootCause: 'Transient voltage spike suppressed by surge protector',
    mttrMinutes: 12
  }
];

export const ALTERNATE_STORM_DATASET: OutageRecord[] = [
  {
    id: 'STORM-201',
    siteId: 'KHI-011',
    siteName: 'Karachi Port Tower',
    region: 'South Region',
    downtimeHours: 14.2,
    availability: 96.05,
    timestamp: '2026-08-24',
    category: 'Commercial Grid Outage',
    status: 'Active',
    slaTarget: 99.90,
    rootCause: 'Monsoon flash flood inundated ground feeder sub-station',
    mttrMinutes: 852
  },
  {
    id: 'STORM-202',
    siteId: 'GWD-005',
    siteName: 'Gwadar Coastline Radar Tower',
    region: 'South Region',
    downtimeHours: 11.0,
    availability: 96.94,
    timestamp: '2026-08-24',
    category: 'Fiber Cut',
    status: 'Active',
    slaTarget: 99.90,
    rootCause: 'Coastal erosion severed buried optical conduit',
    mttrMinutes: 660
  },
  {
    id: 'STORM-203',
    siteId: 'KHI-099',
    siteName: 'Karachi DHA Phase 8 Tower',
    region: 'South Region',
    downtimeHours: 5.5,
    availability: 98.47,
    timestamp: '2026-08-24',
    category: 'Genset Fuel Exhaustion',
    status: 'Active',
    slaTarget: 99.90,
    rootCause: 'Submerged fuel tank intake line',
    mttrMinutes: 330
  }
];
